<?php

namespace App\SalesTax\Interfaces;

use App\SalesTax\Exception\TaxCalculationException;
use App\SalesTax\ValueObjects\SalesTaxInvoice;

interface TaxCalculatorInterface
{
    /**
     * Determines the tax rates that apply to a sales document.
     *
     * @throws TaxCalculationException
     *
     * @return array list of applied taxes as generated by Tax::expandList()
     */
    public function assess(SalesTaxInvoice $salesTaxInvoice): array;

    /**
     * Adjusts the sales tax assessed for a particular document that
     * has previously had sales tax calculated.
     *
     * This will be used overwrite the previously calculated tax amount so
     * the result should return the full tax amount and not just the delta.
     *
     * @throws TaxCalculationException
     *
     * @return array list of applied taxes as generated by Tax::expandList()
     */
    public function adjust(SalesTaxInvoice $salesTaxInvoice): array;

    /**
     * Voids out the sales tax assessed for a sales document.
     *
     * @throws TaxCalculationException
     */
    public function void(SalesTaxInvoice $salesTaxInvoice): void;
}
