<?php

namespace App\Chasing\ValueObjects;

class InvoiceChaseStep
{
    public function __construct(private int $trigger, private array $options, private ?string $id = null)
    {
    }

    public function getId(): ?string
    {
        return $this->id;
    }

    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    public function getTrigger(): int
    {
        return $this->trigger;
    }

    public function getOptions(): array
    {
        return $this->options;
    }

    /**
     * Returns a hash generated by all data except the id.
     */
    public function hash(): string
    {
        $trigger = $this->trigger;
        // get options sorted by keys without modifying class member
        $options = $this->options;
        ksort($options);

        // creat key,value string pairs
        $pairs = ["(trigger:$trigger)"];
        foreach ($options as $key => $value) {
            $pairs[] = "($key:$value)";
        }

        return implode('-', $pairs);
    }

    public function copy(): self
    {
        return new InvoiceChaseStep($this->trigger, $this->options, $this->id);
    }

    /**
     * Determines if the chase step is equal to the one provided.
     *
     * @param bool $strict whether or not to compare ids
     */
    public function equals(InvoiceChaseStep $step, bool $strict = false): bool
    {
        $trigger = $step->getTrigger() == $this->getTrigger();
        $options = $step->getOptions() == $this->getOptions();
        $id = true;
        if ($strict) {
            $id = $step->getId() == $this->getId();
        }

        return $id && $options && $trigger;
    }

    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'trigger' => $this->trigger,
            'options' => $this->options,
        ];
    }
}
