<?php

namespace App\Tests\Sending\Email\Api;

use App\Core\Authentication\Models\User;
use App\Sending\Email\Api\EditInboxThreadRoute;
use App\Sending\Email\Models\EmailThread;
use App\Tests\AppTestCase;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;

class EditInboxThreadRouteTest extends AppTestCase
{
    private static User $user;

    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
        self::hasCompany();
        self::hasCustomer();
        self::hasInbox();
        self::$user = self::getService('test.user_context')->get();
    }

    public function testRun(): void
    {
        $emailThread = new EmailThread();
        $emailThread->inbox = self::$inbox;
        $emailThread->name = 'test';
        $emailThread->status = 'open';
        $emailThread->saveOrFail();

        // test success
        $this->runRequest($emailThread->id, [
            'name' => 'updated',
            'assignee_id' => self::$user->id,
            'customer_id' => self::$customer->id,
            'status' => 'pending',
        ]);
        $emailThread->refresh();
        $this->assertEquals($emailThread->name, 'updated');
        $this->assertEquals($emailThread->status, 'pending');
        $this->assertEquals($emailThread->assignee_id, self::$user->id);
        $this->assertEquals($emailThread->customer_id, self::$customer->id);

        $emailThread->related_to_id = 1;
        $emailThread->saveOrFail();

        // test success 2
        $this->runRequest($emailThread->id, [
            'customer_id' => self::$customer->id,
            'status' => 'closed',
        ]);

        $emailThread->refresh();
        $this->assertEquals($emailThread->status, 'closed');

        // test failed
        $this->expectExceptionMessage('Customer cannot be changed if the thread is related to document');
        $this->runRequest($emailThread->id, [
            'customer_id' => self::$customer->id - 1,
        ]);
    }

    private function runRequest(int $threadId, array $query = []): void
    {
        $request = new Request([], []);
        $request->attributes->set('inbox_id', self::$inbox->id);
        $request->attributes->set('model_id', $threadId);
        foreach ($query as $key => $item) {
            $request->request->set($key, $item);
        }
        $requestStack = new RequestStack();
        $requestStack->push($request);

        $route = new EditInboxThreadRoute();
        $route->setModelClass(EmailThread::class);
        $context = self::getService('test.api_runner')->validateRequest($request, $route->getDefinition());
        $route->buildResponse($context);
    }
}
