<?php

namespace App\Chasing\CustomerChasing;

use App\Chasing\Models\ChasingCadence;
use App\Core\Queue\Queue;
use App\Core\Queue\QueueServiceLevel;
use App\EntryPoint\QueueJob\RunChasingCadenceJob;
use Symfony\Component\Lock\LockFactory;

/**
 * Orchestrates the chasing run for a given customer chasing cadence. This class
 * will invoke the chasing planner and then execute any activities
 * generated by the planner.
 */
class CustomerChasingRun
{
    private const LOCK_TTL = 1800;

    public function __construct(private Queue $queue, private LockFactory $lockFactory, private CustomerChasingPlanner $planner, private CustomerChasingPlanExecutor $executor)
    {
    }

    /**
     * Queues the run to happen later.
     */
    public function queue(ChasingCadence $cadence): void
    {
        $payload = [
            'cadence' => $cadence->id(),
            'tenant_id' => $cadence->tenant_id,
        ];

        $this->queue->enqueue(RunChasingCadenceJob::class, $payload, QueueServiceLevel::Batch);
    }

    /**
     * Executes the chasing cadence.
     */
    public function chase(ChasingCadence $cadence): void
    {
        // grab the mutex lock
        $lock = new CustomerCadenceLock($cadence, $this->lockFactory);
        if (!$lock->acquire(self::LOCK_TTL)) {
            return;
        }

        // switch to the company's time zone before performing date calculations
        $tenant = $cadence->tenant();
        $tenant->useTimezone();

        // mark the cadence last run time as the starting time of the run
        $cadence->last_run = time();
        $cadence->saveOrFail();

        // build and execute the action plan
        $this->executor->execute($tenant, $this->planner->plan($cadence));

        // release the mutex lock
        $lock->release();
    }
}
