<?php

namespace App\Reports\Interfaces;

use App\Reports\ValueObjects\DashboardContext;
use Carbon\CarbonImmutable;

interface DashboardMetricInterface
{
    /**
     * Gets the name of this metric. The metric name should be unique.
     *
     * Allowed characters: lower case alphanumeric, _
     */
    public static function getName(): string;

    /**
     * Generates the metric.
     */
    public function build(DashboardContext $context, array $options): array;

    /**
     * When this option is enabled, then when a new event is added
     * to the activity log, this will invalidate the cached value.
     */
    public function invalidateCacheAfterEvent(): bool;

    /**
     * Gets the time after a value generated by this metric should be invalidated.
     */
    public function getExpiresAt(): CarbonImmutable;
}
