<?php

namespace App\Imports\Interfaces;

use App\Imports\Exceptions\ValidationException;
use App\Imports\Models\Import;
use App\Imports\ValueObjects\ImportResult;

interface ImporterInterface
{
    /**
     * Gets the name of an import.
     */
    public function getName(string $type, array $options): string;

    /**
     * This builds the records that are to be imported into Invoiced.
     * This can also be used to generate a preview of what's going to
     * be imported. Any data will be fetched from external services
     * in this step.
     *
     * @throws ValidationException
     *
     * @return array built import
     */
    public function build(array $mapping, array $lines, array $options, Import $import): array;

    /**
     * Performs the import using the records generated by the build()
     * step.
     */
    public function run(array $records, array $options, Import $import): ImportResult;

    /**
     * Checks if the importer has another batch to process.
     */
    public function hasMore(): bool;

    /**
     * Gets the options for the next import batch.
     */
    public function hasMoreOptions(): array;
}
