<?php

namespace App\Core\Libs;

use App\Core\Utils\IpUtilities;
use Defuse\Crypto\Crypto;
use Defuse\Crypto\Key;
use Psr\Log\LoggerAwareInterface;
use Psr\Log\LoggerAwareTrait;
use Redis;
use Symfony\Component\HttpFoundation\Request;
use Throwable;

class FileByHashFetchRateLimiter implements LoggerAwareInterface
{
    use LoggerAwareTrait;

    const VIEW_LIMIT_PER_IP = 5; // IPs can access a max of 5 files before asking for CAPTCHA verification

    const VIEW_LIMIT_WINDOW = 86400; // 24 hours, time that views are remembered

    private static array $ipIgnore = [
        '52.17.9.21',       // Detectify
        '52.17.98.131',     // Detectify
    ];

    private static array $subnetIgnore = [
        ['67.79.55.184', 29], // Invoiced HQ
    ];

    public function __construct(
        /** @var Redis $redisClient */
        private $redisClient,
        private string $cacheNamespace,
        private Key $encryptionKey
    ) {
    }

    /**
     * Records and verifies that a connected HTTP client is able to
     * access the S3 files without asking for CAPTCHA
     * verification. This attempts to block large-scale
     * data exfiltration and automated crawling activity.
     */
    public function needsCaptchaVerification(string $id, string $ip): bool
    {
        // check if the IP address or subnet should be ignored
        if (in_array($ip, self::$ipIgnore)) {
            return false;
        }

        foreach (self::$subnetIgnore as $entry) {
            [$address, $cidr] = $entry;
            if (IpUtilities::ipInCidr($ip, $address, $cidr)) {
                return false;
            }
        }

        // Track the unique S3 file that are accessed
        // for a given IP by using Redis sets. Each set contains
        // a list of unique user sessions accessed
        // in the last 24 hours.
        $k = $this->cacheNamespace.':s3_file_preview.'.$ip;

        // record the user session being accessed for this IP
        try {
            $this->redisClient->sadd($k, strtolower($id));

            // set the views to expire 24 hours from now
            $this->redisClient->expire($k, self::VIEW_LIMIT_WINDOW);

            // check how many s3 files have been accessed today
            // by using the set's cardinality
            $n = (int) $this->redisClient->scard($k);
        } catch (\RedisException $e) {
            // Fail open so Redis outages don't take down the s3 file access
            $this->logger->error('S3 file access rate limiting call to redis failed', ['exception' => $e]);
            $n = 0;
        }

        return $n > self::VIEW_LIMIT_PER_IP;
    }

    /**
     * Encrypts a URL for a secure redirect.
     */
    public function encryptRedirectUrlParameter(string $url): ?string
    {
        try {
            return Crypto::encrypt($url, $this->encryptionKey);
        } catch (Throwable) {
            return null;
        }
    }

    /**
     * Decrypts a URL generated by encryptRedirectUrlParameter().
     */
    public function decryptRedirectUrlParameter(?string $input): ?string
    {
        try {
            return Crypto::decrypt((string) $input, $this->encryptionKey);
        } catch (Throwable) {
            return null;
        }
    }

    /**
     * Handles a successful CAPTCHA verification response by
     * un-marking the IP as needing verification.
     */
    public function verifiedCaptcha(string $ip): void
    {
        $k = $this->cacheNamespace.':s3_file_preview.'.$ip;

        try {
            $this->redisClient->del($k);
        } catch (\RedisException) {
            // no need to log here because it would have been caught above
        }
    }

    public function isAcmeRequest(Request $request): bool
    {
        $path = $request->getPathInfo();

        return str_contains($path, '/.well-known/acme-challenge');
    }
}
