<?php

namespace App\ActivityLog\Enums;

enum EventType: string
{
    case ChargeFailed = 'charge.failed';
    case ChargePending = 'charge.pending';
    case ChargeSucceeded = 'charge.succeeded';
    case ContactCreated = 'contact.created';
    case ContactDeleted = 'contact.deleted';
    case ContactUpdated = 'contact.updated';
    case CreditNoteCommented = 'credit_note.commented';
    case CreditNoteCreated = 'credit_note.created';
    case CreditNoteDeleted = 'credit_note.deleted';
    case CreditNoteUpdated = 'credit_note.updated';
    case CreditNoteViewed = 'credit_note.viewed';
    case CustomerCreated = 'customer.created';
    case CustomerDeleted = 'customer.deleted';
    case CustomerMerged = 'customer.merged';
    case CustomerUpdated = 'customer.updated';
    case DisputeCreated = 'dispute.created';
    case EmailNotSent = 'email.not_sent';
    case EmailSent = 'email.sent';
    case EstimateApproved = 'estimate.approved';
    case EstimateCommented = 'estimate.commented';
    case EstimateCreated = 'estimate.created';
    case EstimateDeleted = 'estimate.deleted';
    case EstimateUpdated = 'estimate.updated';
    case EstimateViewed = 'estimate.viewed';
    case ImportFinished = 'import.finished';
    case InvoiceCommented = 'invoice.commented';
    case InvoiceCreated = 'invoice.created';
    case InvoiceDeleted = 'invoice.deleted';
    case InvoicePaid = 'invoice.paid';
    case InvoicePaymentExpected = 'invoice.payment_expected';
    case InvoiceUpdated = 'invoice.updated';
    case InvoiceViewed = 'invoice.viewed';
    case LetterSent = 'letter.sent';
    case LineItemCreated = 'line_item.created';
    case LineItemDeleted = 'line_item.deleted';
    case LineItemUpdated = 'line_item.updated';
    case NetworkDocumentReceived = 'network_document.received';
    case NetworkDocumentSent = 'network_document.sent';
    case NetworkDocumentStatusUpdated = 'network_document.status_updated';
    case NoteCreated = 'note.created';
    case NoteDeleted = 'note.deleted';
    case NoteUpdated = 'note.updated';
    case PaymentCreated = 'payment.created';
    case PaymentDeleted = 'payment.deleted';
    case PaymentLinkCompleted = 'payment_link.completed';
    case PaymentLinkCreated = 'payment_link.created';
    case PaymentLinkDeleted = 'payment_link.deleted';
    case PaymentLinkUpdated = 'payment_link.updated';
    case PaymentPlanCreated = 'payment_plan.created';
    case PaymentPlanDeleted = 'payment_plan.deleted';
    case PaymentPlanUpdated = 'payment_plan.updated';
    case PaymentSourceCreated = 'payment_source.created';
    case PaymentSourceDeleted = 'payment_source.deleted';
    case PaymentSourceUpdated = 'payment_source.updated';
    case PaymentUpdated = 'payment.updated';
    case PayoutCreated = 'payout.created';
    case PayoutFailed = 'payout.failed';
    case PromiseToPayBroken = 'promise_to_pay.broken';
    case RefundCreated = 'refund.created';
    case SubscriptionCanceled = 'subscription.deleted';
    case SubscriptionCreated = 'subscription.created';
    case SubscriptionUpdated = 'subscription.updated';
    case TaskCompleted = 'task.completed';
    case TaskCreated = 'task.created';
    case TaskDeleted = 'task.deleted';
    case TaskUpdated = 'task.updated';
    case TextMessageSent = 'text_message.sent';
    case TransactionCreated = 'transaction.created';
    case TransactionDeleted = 'transaction.deleted';
    case TransactionUpdated = 'transaction.updated';
    case VendorAdjustmentCreated = 'vendor_adjustment.created';
    case VendorAdjustmentDeleted = 'vendor_adjustment.deleted';
    case VendorAdjustmentUpdated = 'vendor_adjustment.updated';
    case VendorCreated = 'vendor.created';
    case VendorDeleted = 'vendor.deleted';
    case VendorPaymentCreated = 'vendor_payment.created';
    case VendorPaymentDeleted = 'vendor_payment.deleted';
    case VendorPaymentUpdated = 'vendor_payment.updated';
    case VendorUpdated = 'vendor.updated';

    public function toInteger(): int
    {
        return match ($this) {
            self::ChargeFailed => 1,
            self::ContactCreated => 2,
            self::ContactUpdated => 3,
            self::ContactDeleted => 4,
            self::CreditNoteCreated => 5,
            self::CreditNoteUpdated => 6,
            self::CreditNoteDeleted => 7,
            self::CreditNoteViewed => 8,
            self::CreditNoteCommented => 9,
            self::CustomerCreated => 10,
            self::CustomerUpdated => 11,
            self::CustomerDeleted => 12,
            self::CustomerMerged => 13,
            self::EmailSent => 14,
            self::EmailNotSent => 15,
            self::EstimateCreated => 16,
            self::EstimateUpdated => 17,
            self::EstimateDeleted => 18,
            self::EstimateViewed => 19,
            self::EstimateCommented => 20,
            self::EstimateApproved => 21,
            self::ImportFinished => 22,
            self::InvoiceCreated => 23,
            self::InvoiceUpdated => 24,
            self::InvoiceDeleted => 25,
            self::InvoiceCommented => 26,
            self::InvoiceViewed => 27,
            self::InvoicePaymentExpected => 28,
            self::InvoicePaid => 29,
            self::LetterSent => 30,
            self::LineItemCreated => 31,
            self::LineItemUpdated => 32,
            self::LineItemDeleted => 33,
            self::NoteCreated => 34,
            self::NoteUpdated => 35,
            self::NoteDeleted => 36,
            self::PaymentCreated => 37,
            self::PaymentUpdated => 38,
            self::PaymentDeleted => 39,
            self::PaymentPlanCreated => 40,
            self::PaymentPlanUpdated => 41,
            self::PaymentPlanDeleted => 42,
            self::PaymentSourceCreated => 43,
            self::PaymentSourceUpdated => 44,
            self::PaymentSourceDeleted => 45,
            self::RefundCreated => 46,
            self::SubscriptionCreated => 47,
            self::SubscriptionUpdated => 48,
            self::SubscriptionCanceled => 49,
            self::TaskCreated => 50,
            self::TaskUpdated => 51,
            self::TaskDeleted => 52,
            self::TaskCompleted => 53,
            self::TextMessageSent => 54,
            self::TransactionCreated => 55,
            self::TransactionUpdated => 56,
            self::TransactionDeleted => 57,
            self::VendorCreated => 58,
            self::VendorUpdated => 59,
            self::VendorDeleted => 60,
            self::NetworkDocumentSent => 61,
            self::NetworkDocumentReceived => 62,
            self::NetworkDocumentStatusUpdated => 63,
            self::VendorAdjustmentCreated => 64,
            self::VendorAdjustmentDeleted => 65,
            self::VendorAdjustmentUpdated => 66,
            self::VendorPaymentCreated => 67,
            self::VendorPaymentDeleted => 68,
            self::VendorPaymentUpdated => 69,
            self::PromiseToPayBroken => 70,
            self::PaymentLinkCreated => 71,
            self::PaymentLinkDeleted => 72,
            self::PaymentLinkUpdated => 73,
            self::PaymentLinkCompleted => 74,
            self::PayoutCreated => 75,
            self::ChargePending => 76,
            self::ChargeSucceeded => 77,
            self::DisputeCreated => 78,
            self::PayoutFailed => 79,
        };
    }
}
